import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";


export const metadata: Metadata = {
  title: "Fresh Harvest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`rubi antialiased bg-gray-50`}
      >
        <div className="fixed z-10 w-full ">
          <Navbar/>
        </div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
